# Generated by Django 4.2 on 2023-04-17 09:36

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('api', 'Student')
    Student(name="Joe Silver", email="joe@email.com", document="22342342", phone="00000000").save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]